version: 2

sources:
  - name: raw
    database: "{{ target.project }}"
    schema: "{{ target.dataset }}"
    tables:
      - name: raw_customers
        external:
          location: "gs://jaffleshop-483809/csv/raw_customers.csv"
          options:
            format: csv
            skip_leading_rows: 1
        columns:
          - name: id
            data_type: int64
          - name: first_name
            data_type: string
          - name: last_name
            data_type: string
      - name: raw_orders
        external:
          location: "gs://jaffleshop-483809/csv/raw_orders.csv"
          options:
            format: csv
            skip_leading_rows: 1
        columns:
          - name: id
            data_type: int64
          - name: user_id
            data_type: int64
          - name: order_date
            data_type: date
          - name: status
            data_type: string
      - name: raw_payments
        external:
          location: "gs://jaffleshop-483809/csv/raw_payments.csv"
          options:
            format: csv
            skip_leading_rows: 1
        columns:
          - name: id
            data_type: int64
          - name: order_id
            data_type: int64
          - name: payment_method
            data_type: string
          - name: amount
            data_type: int64
